# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Frazier
email: nick@nickfrazier.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Nick Frazier, and I like to make things. This site is my way of
  sharing some of what I've done with you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fraziern.github.io" # the base hostname & protocol for your site
twitter_username: nrf
github_username: fraziern
codepen_username: fraziern

# Build settings
markdown: kramdown

# Non-posts
collections:
  projects:
    output: true
